require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/HelperInstanceVariable:
  Enabled: false
