require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/HelperInstanceVariable:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

# private 以下は一段下げる
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

NumericLiterals:
    MinDigits: 7
